[stations]
selected_profile = "Default"

[stations.profiles.Default]
include = []
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
    "*_DEL",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.Default.aliases]

[stations.profiles.1_EPWW_RADAR]
include = [
    "EP*",
    "EDMM*G*CTR",
    "EDMM*H*CTR",
    "EDMM*M*CTR",
    "EDWW_CTR",
    "EDWW*B*CTR",
    "EDWW*F*CTR",
    "EDWW*M*CTR",
    "EDUU*H*CTR",
    "EDUU*O*CTR",
    "EDUU*OH*CTR",
    "EDUU*SPE*CTR",
    "EDUU*SAL*CTR",
    "EDAH*TWR",
    "EDDB*N*APP",
    "EDDB*S*APP",
    "EDDB*DEP",
    "EDDC*S*APP",
    "EDDP*TRS*APP",
    "EKDK_CTR",
    "EKDK*A*CTR",
    "EKDK*C*CTR",
    "ESAA*CTR",
    "ESMM*2*CTR",
    "ESMM*5*CTR",
    "ESMM*6*CTR",
    "ESMM*7*CTR",
    "ESMM*8*CTR",
    "ESMM*9*CTR",
    "ESMM*K*CTR",
    "EY*CTR",
    "EYKA_I*_APP",
    "LK*CTR",
    "LKPR*APP",
    "LKMT*APP",
    "LZBB*CTR",
    "LZTT*TWR",
    "UKLV*CTR",
    "UKLL*APP",
    "UKLU*TWR",
    "UKR*CTR",
    "UMKK*CTR",
    "UMMV*CTR",
    "UMBB*TWR",
]
exclude = [
    "LKAA*S*CTR",
    "LKAA*W*CTR",
    "UMMV*S*CTR",
    "EDMM_NDG_CTR",
]
priority = [
    "EPWW*",
    "EP*_APP",
    "EP*_TWR",
    "ED*",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "FirAndIcao"

[stations.profiles.1_EPWW_RADAR.aliases]
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"132.700" = "ACC N"
"123.625" = "ACC R"
"128.250" = "APP DE"
"127.280" = "APP GD"
"133.660" = "APP GD L"
"121.075" = "APP KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"126.530" = "DIR KK"
"135.405" = "DIR KT"
"120.750" = "APP KS P"
"128.925" = "APP PO N"
"123.040" = "APP PO S"
"128.805" = "APP WA"
"129.380" = "APP WA F"
"125.055" = "APP WA N"
"135.930" = "APP WA S"
"134.875" = "FIS EPWW"
"127.150" = "FIS GD"
"119.275" = "FIS KK"
"126.300" = "FIS PO"
"118.775" = "FIS WA N"
"119.450" = "FIS WA S"
"131.005" = "EPBY TWR"
"122.750" = "EPDE TWR"
"118.105" = "EPGD TWR"
"123.255" = "EPKK TWR"
"121.025" = "EPKS TWR"
"136.430" = "EPLB TWR"
"124.230" = "EPLL TWR"
"123.930" = "EPMO TWR"
"119.980" = "EPPO TWR"
"118.430" = "EPRA TWR"
"126.805" = "EPRZ TWR"
"121.255" = "EPSC TWR"
"118.030" = "EPSY TWR"
"118.305" = "EPWA TWR"
"120.255" = "EPWR TWR"
"118.755" = "EPZG TWR"
"132.830" = "EDAH TWR"
"119.630" = "EDDB APP N"
"126.425" = "EDDB APP S"
"120.630" = "EDDB S DEP"
"125.875" = "EDDC SAS"
"126.175" = "EDDP TRS"
"133.230" = "EDMM GER"
"118.235" = "EDMM HAL"
"133.565" = "EDMM HOF"
"124.960" = "EDMM MEI"
"128.235" = "EDUU H12"
"133.035" = "EDUU O12"
"126.785" = "EDUU O22"
"133.860" = "EDUU SAL"
"133.285" = "EDUU SPE"
"133.725" = "EDWW ACC"
"123.225" = "EDWW B"
"136.450" = "EDWW FLG"
"136.050" = "EDWW MAR"
"124.175" = "EDWW MRZ"
"135.290" = "EKDK A"
"136.555" = "EKDK ACC"
"128.215" = "EKDK C"
"126.825" = "ESAA ACC"
"132.765" = "ESMM 5"
"135.805" = "ESMM 6"
"124.155" = "ESMM 7"
"128.180" = "ESMM 8"
"135.985" = "ESMM 9"
"131.280" = "ESMM K"
"124.605" = "EYKA FIS"
"133.305" = "EYVL ACC"
"135.380" = "EYVL E"
"133.430" = "EYVL M"
"132.280" = "EYVL U"
"127.125" = "LKAA ACC"
"126.100" = "LKAA FIS"
"135.135" = "LKAA L"
"127.825" = "LKAA N"
"124.050" = "LKAA R"
"133.410" = "LKAA S"
"133.425" = "LKAA U"
"127.575" = "LKPR APP"
"119.375" = "LKMT APP"
"134.475" = "LZBB ACC"
"124.300" = "LZBB FIS"
"127.425" = "LZBB U"
"121.350" = "LZTT TWR"
"120.525" = "UKLL APP"
"126.900" = "UKLU TWR"
"134.050" = "UKLV ACC"
"123.475" = "UKR CTR"
"127.700" = "UMBB TWR"
"123.700" = "UMKK ACC"
"135.700" = "UMMV ACC"
"124.825" = "UMMV W"
"119.125" = "UMMV N"


[stations.profiles.EPWW_TWR]
include = ["EP*"]
exclude = []
priority = [
    "EPWW*",
    "EP*_APP",
    "EP*_TWR",
    "EP*_GND",
    "EP*_DEL",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "Icao"

[stations.profiles.EPWW_TWR.aliases]
"119.180" = "BABICE INFO"
"123.205" = "BIALYSTOK RADIO"
"118.330" = "BIELSKO RADIO"
"131.005" = "TWR BY"
"124.480" = "DAJTKI RADIO"
"122.750" = "TWR DE"
"128.250" = "APP DE"
"131.330" = "GND GD"
"118.105" = "TWR GD"
"127.280" = "APP GD"
"133.660" = "APP GD L"
"118.260" = "GLIWICE RADIO"
"126.855" = "GRADY RADIO"
"122.830" = "JASTARNIA RADIO"
"124.080" = "DEL KT"
"121.805" = "GND KT"
"129.255" = "TWR KT"
"135.405" = "DIR KT"
"120.080" = "KATOWICE RADIO"
"119.405" = "KIKITY RADIO"
"121.980" = "DEL KK"
"123.255" = "TWR KK"
"121.075" = "APP KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"126.530" = "DIR KK"
"119.555" = "KROSNO RADIO"
"121.025" = "TWR KS"
"120.750" = "APP KS P"
"136.430" = "TWR LB"
"120.005" = "DEL LL"
"124.230" = "TWR LL"
"118.080" = "MASLOW RADIO"
"119.105" = "MIELEC INFO"
"119.680" = "DEL MO"
"123.930" = "TWR MO"
"122.305" = "NOWY TARG RADIO"
"118.605" = "POBIEDNIK RADIO"
"124.140" = "GND PO"
"119.980" = "TWR PO"
"128.925" = "APP PO N"
"123.040" = "APP PO S"
"122.600" = "PRZASNYSZ RADIO"
"130.780" = "PRZYLEP RADIO"
"121.750" = "GND M RA"
"118.430" = "TWR RA"
"121.390" = "RADAWIEC RADIO"
"126.805" = "TWR RZ"
"121.255" = "TWR SC"
"118.030" = "TWR SY"
"121.605" = "DEL WA"
"121.905" = "GND WA"
"118.305" = "TWR WA"
"128.805" = "APP WA"
"125.055" = "APP WA N"
"135.930" = "APP WA S"
"129.380" = "APP WA F"
"120.255" = "TWR WR"
"122.805" = "ZAR RADIO"
"118.755" = "TWR ZG"
"134.875" = "FIS EPWW"
"127.150" = "FIS GD"
"119.275" = "FIS KK"
"126.300" = "FIS PO"
"118.775" = "FIS WA N"
"119.450" = "FIS WA S"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"132.700" = "ACC N"
"123.625" = "ACC R"


[stations.profiles.EPGD_TWR]
include = [
    "EPWW*",
    "EPGD*",
    "EPBY*_TWR"
]
exclude = []
priority = [
    "EPGD*GND",
    "EPGD*TWR",
    "EPGD_APP",
    "EPGD_*_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPGD_TWR.aliases]
"131.330" = "GND GD"
"118.105" = "TWR GD"
"127.280" = "APP GD"
"133.660" = "APP GD L"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"127.150" = "FIS GD"
"131.005" = "TWR BY"

[stations.profiles.EPKK_TWR]
include = [
    "EPWW*",
    "EPKK*",
    "EPKT*_TWR",
    "EPRZ*_TWR",
    "EPKP*"
]
exclude = []
priority = [
    "EPKK*DEL",
    "EPKK*GND",
    "EPKK*TWR",
    "EPKK_*_APP",
    "EPKK?_APP",
    "EPKK_KK?_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPKK_TWR.aliases]
"121.980" = "DEL KK"
"118.105" = "GND KK"
"123.255" = "TWR KK"
"121.075" = "APP KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"126.530" = "DIR KK"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"119.275" = "FIS KK"
"129.255" = "TWR KT"
"135.405" = "DIR KT"
"126.805" = "TWR RZ"
"118.605" = "RADIO KP"

[stations.profiles.EPKT_TWR]
include =  [
    "EPWW*",
    "EPKK*",
    "EPKT*",
    "EPRZ*_TWR",
    "EPKP*",
    "EPKM*",
    "EPGL*"
]
exclude = [
    "EPKK*_GND",
    "EPKK*_DEL"
]
priority = [
    "EPKT*DEL",
    "EPKT*GND",
    "EPKT*TWR",
    "EPKK*_APP",
    "EPKK_*_APP",
    "EPKK_KK?_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPKT_TWR.aliases]
"124.080" = "DEL KT"
"121.805" = "GND KT"
"129.255" = "TWR KT"
"135.405" = "DIR KT"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"119.275" = "FIS KK"
"121.075" = "APP KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"126.530" = "DIR KK"
"123.255" = "TWR KK"
"126.805" = "TWR RZ"
"120.080" = "RADIO KM"
"118.260" = "RADIO GL"

[stations.profiles.EPMO_TWR]
include = [
    "EPWW*",
    "EPWA*",
    "EPMO*",
    "EPBC*"
]
exclude = [
    "EPWA*_GND",
    "EPWA*_DEL",
    "EPWA*_FMP"
]
priority = [
    "EPMO*DEL",
    "EPMO*TWR",
    "EPWA_APP",
    "EPWA_*_APP",
    "EPWW*",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPMO_TWR.aliases]
"119.680" = "DEL MO"
"123.930" = "TWR MO"
"128.805" = "APP WA"
"125.055" = "APP WA N"
"135.930" = "APP WA S"
"129.380" = "APP WA F"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"118.775" = "FIS WA N"
"119.450" = "FIS WA S"
"118.305" = "TWR WA"
"119.180" = "INFO BC"

[stations.profiles.EPPO_TWR]
include = [
    "EPWW*",
    "EPPO*",
    "EPWR*_TWR",
    "EPZG*_TWR"
]
exclude = []
priority = [
    "EPPO*DEL",
    "EPPO*GND",
    "EPPO*TWR",
    "EPPO_N_APP",
    "EPPO_*_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPPO_TWR.aliases]
"121.805" = "DEL PO"
"124.140" = "GND PO"
"119.980" = "TWR PO"
"128.925" = "APP PO N"
"123.040" = "APP PO S"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"126.300" = "FIS PO"
"118.755" = "TWR ZG"
"120.255" = "TWR WR"

[stations.profiles.EPRZ_TWR]
include = [
    "EPWW*",
    "EPKK*",
    "EPKT*_TWR",
    "EPRZ*",
    "EPML*"
]
exclude = [
    "EPKK*_DEL",
    "EPKK*_GND"
]
priority = [
    "EPRZ*GND",
    "EPRZ*TWR",
    "EPKK_RZ?_APP",
    "EPKK_*_APP",
    "EPKK?_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPRZ_TWR.aliases]
"121.805" = "GND RZ"
"126.805" = "TWR RZ"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"119.275" = "FIS KK"
"121.075" = "APP KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"126.530" = "DIR KK"
"135.405" = "DIR KT"
"123.255" = "TWR KK"
"129.255" = "TWR KT"
"119.105" = "INFO ML"

[stations.profiles.EPWA_TWR]
include = [
    "EPWW*",
    "EPWA*",
    "EPMO*_TWR",
    "EPBC*"
]
exclude = []
priority = [
    "EPWA*DEL",
    "EPWA*GND",
    "EPWA*TWR",
    "EPWA_APP",
    "EPWA_*_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPWA_TWR.aliases]
"121.605" = "DEL WA"
"121.905" = "GND WA"
"118.305" = "TWR WA"
"128.805" = "APP WA"
"125.055" = "APP WA N"
"135.930" = "APP WA S"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"118.775" = "FIS WA N"
"119.450" = "FIS WA S"
"123.930" = "TWR MO"
"119.180" = "INFO BC"

[stations.profiles.EPWR_TWR]
include = [
    "EPWW*",
    "EPPO*",
    "EPWR*",
    "EPZG*"
]
exclude = [
    "EPPO*_GND",
    "EPPO*_DEL"
]
priority = [
    "EPWR*DEL",
    "EPWR*GND",
    "EPWR*TWR",
    "EP*_TWR",
    "EPPO_S?_APP",
    "EPPO_*_APP",
    "EPWW*",
    "EP*_TWR",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.EPWR_TWR.aliases]
"124.565" = "DEL WR"
"121.805" = "GND WR"
"120.255" = "TWR WR"
"134.875" = "FIS EPWW"
"125.450" = "ACC (BB)"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"123.625" = "ACC R"
"132.700" = "ACC N"
"126.300" = "FIS PO"
"128.925" = "APP PO N"
"123.040" = "APP PO S"
"119.980" = "TWR PO"
"118.755" = "TWR ZG"

[stations.profiles.EPWW_P_TWR]
include = [
    "EPWW*",
    "EP*_TWR",
    "EPLL*",
    "EPRZ*",
    "EP*_APP",
    "EDMM*G*CTR",
    "EDMM*H*CTR",
    "EDMM*M*CTR",
    "EDWW_CTR",
    "EDWW*B*CTR",
    "EDWW*F*CTR",
    "EDWW*M*CTR",
    "EDUU*H*CTR",
    "EDUU*O*CTR",
    "EDUU*OH*CTR",
    "EDUU*SPE*CTR",
    "EDUU*SAL*CTR",
    "EDAH*TWR",
    "EDDB*N*APP",
    "EDDB*S*APP",
    "EDDB*DEP",
    "EDDC*S*APP",
    "EDDP*TRS*APP",
    "EKRN*TWR",
]
exclude = [
        "EDMM_NDG_CTR",
]
priority = [
    "EP*_TWR",
    "EP*_APP",
    "EPWW*",
    "ED*",
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "Icao"

[stations.profiles.EPWW_P_TWR.aliases]
#   ACC
"125.450" = "ACC (BB)"
"134.875" = "FIS EPWW"
"130.625" = "ACC HI"
"127.025" = "ACC B"
"133.475" = "ACC C"
"134.225" = "ACC D"
"120.950" = "ACC E"
"129.075" = "ACC F"
"124.925" = "ACC G"
"124.625" = "ACC J"
"132.700" = "ACC N"
"123.625" = "ACC R"
#   APPROACH
"128.805" = "APP WA"
"125.055" = "APP WA N"
"118.775" = "FIS WA N"
"135.930" = "APP WA S"
"119.450" = "FIS WA S"
"129.380" = "APP WA F"
"121.075" = "APP KK"
"119.275" = "FIS KK"
"126.975" = "APP KK E"
"133.030" = "APP KK RZ"
"135.405" = "DIR KT"
"126.530" = "DIR KK"
"127.280" = "APP GD"
"127.150" = "FIS GD"
"133.660" = "APP GD L"
"128.925" = "APP PO N"
"126.300" = "FIS PO"
"123.040" = "APP PO S"
"128.250" = "APP DE"
"120.750" = "APP KS P"
#   TOWER
"118.305" = "TWR WA"
"123.930" = "TWR MO"
"123.255" = "TWR KK"
"129.255" = "TWR KT"
"126.805" = "TWR RZ"
"118.105" = "TWR GD"
"131.005" = "TWR BY"
"119.980" = "TWR PO"
"120.255" = "TWR WR"
"118.755" = "TWR ZG"
"118.030" = "TWR SY"
"136.430" = "TWR LB"
"124.230" = "TWR LL"
"118.430" = "TWR RA"
"121.025" = "TWR KS"
"121.255" = "TWR SC"
#   GROUND
"121.805" = "GND RZ"
#   DELIVERY
"120.005" = "DEL LL"
#   FOREIGN
"132.830" = "EDAH TWR"
"119.630" = "EDDB APP N"
"126.425" = "EDDB APP S"
"120.630" = "EDDB DEP S"
"125.875" = "EDDC APP SAS"
"126.175" = "EDDP APP TRS"
"133.230" = "EDMM GER"
"118.235" = "EDMM HAL"
"133.565" = "EDMM HOF"
"124.960" = "EDMM MEI"
"134.150" = "EDMM ZUG"
"133.725" = "EDWW ACC"
"123.225" = "EDWW B"
"136.450" = "EDWW FLG"
"136.050" = "EDWW MAR"
"124.175" = "EDWW MRZ"
"133.035" = "EDUU O12"
"126.785" = "EDUU O22"
"128.235" = "EDUU H12"
"133.860" = "EDUU SAL"
"133.285" = "EDUU SPE"
"135.985" = "ESMM 9"
